config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  resources :items do
    member do
      get :toggle # 찜하기
      get :add # 장바구니 추가
    end
  end

  resources :orders
  resources :line_items
  resources :user_items
  resources :comments
  root "items#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  def self.generate_categories
    %w(식품/생활
    패션/뷰티
    가전/디지털
    여행/레저).each_with_index do |category_title, index|
      Category.create(title: category_title, position: index)
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :item, optional: true
end

app/models/item.rb
class Item < ApplicationRecord
  mount_uploader :image, ImageUploader

  belongs_to :user, optional: true
  belongs_to :category, optional: true

  has_many :line_items, dependent: :nullify
  # 상품이 삭제되도 주문 항목은 삭제되면 안 됨
  has_many :user_items, dependent: :destroy
  # 찜하기는 상품이 삭제되면 삭제되어도 됨(어차피 삭제된 상품 확인할 수 없음)

  has_many :comments, dependent: :destroy

  def self.generate_items
    %w(아이폰 안드로이드 아이패드 맥북 시계 애플워치 갤럭시기어).each do |title|
      category = Category.first
      Item.create(title: title, price: 2000000, category: category, image: Item.first.image, user: User.first)
    end
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :item, optional: true

  # 상품이 삭제되어도 기존에 주문한 주문 항목은 남아있어야 해서 optional로 정의하고
  # item 쪽에 has_many 할 떄는 destroy 대신 nullify

  # line_item이 변경될 떄마다 주문의 총 가격 변경하기
  # line_item 본인을 변경할 때는 after_save 후 update 하지 말고(재귀함수처럼 계속)
  # before_save 하고 update 대 = 로 할당만 해서 save할 때 한 번에 저장되도록 처리하는 것이 좋음

  # line_item 본인이 아니라 order를 수정하는 것이므로  after_save 후 order.update를 해도 될듯

  # after_save :set_order_total
  after_destroy :set_order_total

  def set_order_total
    puts "set_order_total"
    order.update(total: order.line_items.sum("amount * price"))
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, optional: true
  enum status: [:cart, :paid, :canceled]

  has_many :line_items, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_items, dependent: :destroy # 찜하기는 회원이 삭제되거나 탈퇴하면 지워져도 됨
  has_many :items, dependent: :nullify # 등록된 상품은 등록한 회원이 삭제되더라도
  # 주문이나 리뷰 등 다른 데이터와 많이 엮여 있어서 삭제하지 않고 foreign_key만 null로 갱신

  has_many :comments, dependent: :nullify

  has_many :orders
  def has_item? item
    user_items.where(item: item).present?
  end
end

app/models/user_item.rb
class UserItem < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def get_cart
    # 현재 로그인한 유저가 가진 주문 중 cart 상태의 주문을 하나 찾아서 가져오거나
    # 없으면 하나 새로 생성함
    current_user.orders.cart.first_or_create
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create comment_params
    # redirect_to item_path(comment.item)
  end

  def update
    comment = Comment.find_by(id: params[:id])
    comment.update(commnet_params) if comment
    redirect_to item_path(comment.item)
  end

  def destroy
    @comment = Comment.find_by(id: params[:id])
    # byebug
    @comment.destroy if @comment
    # redirect_to item_path(comment.item)
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :user_id, :item_id)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show] # 찜하기 로그인 해야 사용 가능
  before_action :load_object, only: [:show, :toggle, :edit, :update, :destroy, :add] # 상품 상세와 찜하기는 @item을 먼저 불러옴
  before_action :check_owner, only: [:edit, :update, :destroy] # 수정/삭제는 상품 소유자만 할 수 있도록

  def index
    # 내가 판매하는 상품
    if params[:type] == "selling"
      redirect_to root_path, notice: "로그인을 해야 합니다" unless current_user
      @items = current_user.items
    else
      @items = Item.all
      # 카테고리별 페이지
      if params[:category_id].present?
        @category = Category.find(params[:category_id])
        @items = @items.where(category_id: params[:category_id])
      end
    end
    # byebug
    @items = @items.ransack(title_or_description_cont: params[:q]).result(distinct: true) if params[:q].present?
    @items = params[:order].blank? ? @items.order(created_at: :desc) : @items.order(params[:order])
    @items = @items.page(params[:page]).per(20)
  end

  def toggle
    if user_item = current_user.user_items.where(item: @item).first
      # 이미 찜한 상태라면 해제
      user_item.destroy
      flash[:notice] = "찜을 제거하였습니다."
    else
      # 찜한 상태가 아니면 찜하기
      current_user.user_items.where(item: @item).create
      flash[:notice] = "찜하였습니다."
    end
    redirect_to @item
  end

  def add
    # edit은 판매자가 상품 편집을 하는데 사용
    @order = get_cart
    # orders_controller.rb
      # def get_cart
      #   # 현재 로그인한 유저가 가진 주문 중 cart 상태의 주문을 하나 찾아서 가져오거나
      #   # 없으면 하나 새로 생성함
      #   current_user.orders.cart.first_or_create
      # end
      # byebug
    line_item = @order.line_items.where(item: @item).first_or_create(price: @item.price)
    line_item.increment!(:amount)
    line_item.set_order_total
    # line_item.rb
      # def set_order_total
      #   order.update(total: order.line_items.sum("amount * price"))
      # end
    redirect_to new_order_path, notice: "장바구니에 상품을 담았습니다."
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.create(item_params)
    # @item.update(user: current_user)
    redirect_to items_path(type: :selling), notice: "상품을 등록했습니다."
  end

  def edit
  end

  def update
    @item.update(item_params)
    redirect_to items_path(type: :selling), notice: "상품을 수정했습니다."
  end

  def destroy
    @item.destroy
    redirect_back fallback_location: root_path
  end

  def show
  end

  private

    def load_object
      @item = Item.find params[:id]
    end

    def item_params
      params.require(:item).permit(:title, :price, :description, :image, :category_id, :user_id)
    end

    def check_owner
      redirect_to root_path, notice: "권한이 없습니다." unless @item.user == current_user
    end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  def destroy
    @line_item = LineItem.find(params[:id])
    @line_item.destroy
    

    # @order = Order.find(params[:id])
    # redirect_back fallback_location: root_path
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  # 다른 사람도 주문 아이디만 알면 접근이 간으한 상태이므로 내 주문은 나만 볼수 있도 권한 체크
  before_action :load_object, :check_owner, only: [:edit, :show, :update]


  def new
    @order = get_cart
    
  end

  def edit

  end

  def update
    @order.paid!
    @order.update(paid_at: Time.now)
    redirect_to @order
  end

  def index
    @orders = current_user.orders.order(:paid_at).page(params[:page]).per(10)
  end

  private

  def load_object
    @order = Order.find(params[:id])
  end

  def check_owner
    redirect_to(root_path, notice: "권한이 없습니다") unless (@order.user == current_user)
  end
end

app/controllers/user_items_controller.rb
class UserItemsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user_items = current_user.user_items.page(params[:page]).per(10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/user_items_helper.rb
module UserItemsHelper
end

app/views/comments/_comment.html.erb
<% comment ||= nil %>
<% if comment %>
  <div class="list-group-item list-group-item-action" data-id="<%= comment.id %>">
    <div class="row">
      <div class="col-md-2"><%= comment.user&.email %></div>
      <div class="col-md-7"><%= comment.content %></div>
      <div class="col-md-3 text-right">
        <!-- <%# link_to "수정", edit_comment_path(comment) %> / -->
        <% if current_user == comment.user %>
          <%= link_to "삭제", comment, method: :delete, class: "text-danger", remote: true %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/comments/_comments.html.erb
<% comments ||= [] %>

<div class="list-group">
  <% if comments.present? %>
    <% comments.each do |comment| %>
      <%= render 'comments/comment', comment: comment %>
    <% end %>
  <% else %>
    <div class="list-group-item list-group-item-action">
      <h6>댓글이 없습니다.</h6>
    </div>
  <% end %>
</div>

app/views/comments/_form.html.erb
<% comment ||= nil %>
<% item ||= nil %>
<% user ||= nil %>
<% if comment && item && user %>

  <hr>
  <div class="form-group">
    <%= form_for comment, remote: true do |f| %>
      <%= f.text_area :content, class: "form-control" %>
      <div class="row p-3 justify-content-end">
        <%= f.submit "댓글 작성", class: "btn btn-secondary" %>
      </div>
      <%= f.hidden_field :item_id, value: item.id %>
      <%= f.hidden_field :user_id, value: user.id %>
    <% end %>
  </div>
<% end %>

app/views/comments/create.js.erb
alert("댓글이 등록되었습니다.");
$(".list-group").prepend("<%= j render 'comments/comment', comment: @comment %>");
$("#comment_content").val("");

app/views/comments/destroy.js.erb
alert("삭제되었습니다.");
$(".list-group-item[data-id='<%= @comment.id %>']").remove();

app/views/items/_form.html.erb
<div class="container my-5">
  <div class="row">
    <div class="card col-md-6 offset-md-3 p-5">
      <%= form_for @item do |f| %>
        <% if not @item.id %>
          <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, required: true, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, required: true, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :price %>
            <%= f.text_field :price, required: true, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :image %>
            <%= f.file_field :image, required: true, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :category %>
            <%= f.select :category_id, options_for_select(Category.order(:position).map {|category| [category.title, category.id]}), {}, required: true, class: "form-control" %>
          </div>
          <%= f.submit "상품 등록", class: "btn btn-primary" %>
          <%= f.hidden_field :user_id, value: current_user.id %>
          <!-- <% hidden_field_tag :user_id, current_user.id%> -->
        <% else %>
          <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :price %>
            <%= f.text_field :price, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :image %>
            <%= f.file_field :image, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :category %>
            <%= f.select :category_id, options_for_select(Category.order(:position).map {|category| [category.title, category.id]}), {}, class: "form-control" %>
          </div>
          <%= f.submit "상품 등록", class: "btn btn-primary" %>
          <%= f.hidden_field :user_id, value: current_user.id %>
          <!-- <% hidden_field_tag :user_id, current_user.id%> -->
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/items/edit.html.erb
<%= render "form" %>

app/views/items/index.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-12 mb-2">
      <% if params[:type] == "selling"%>
        <h2>나의 상품</h2>
      <% elsif @category %>
        <h2><%= @category.title %></h2>
      <% end %>
      <hr>
      <%= form_tag request.parameters, method: :get do %>
        <div class="form-inline float-left">
          <%= text_field_tag :q, params[:q], class: "form-control mr-1" %>
          <%#= hidden_field_tag :category_id, params[:category_id] %>
          <% if params[:category_id].present? %>
            <%= hidden_field_tag :category_id, @category.id %>
          <% end %>
          <%= submit_tag "검색", class: "btn btn-primary mr-1"%>

        </div>
        <div class="float-right">
          <div class="btn-group">
            <%= link_to "가격순", request.parameters.merge(order: :price), class: "btn btn-#{params[:order].present? ? "secondary" : "outline-secondary"}" %>
            <%= link_to "등록순", request.parameters.merge(order: nil), class: "btn btn-#{params[:order].blank? ? "secondary" : "outline-secondary"}" %>
          </div>
          <%= link_to "상품 등록", new_item_path, class: "btn btn-primary" %>
        </div>

      <% end %>
    </div>

    <% @items.each do |item| %>
      <div class="col-md-3 mb-4">
        <div class="card">
          <img class="card-img-top" src="<%= item.image.url(:thumb) if item.image? %>"  alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title"><%= item.title %></h5>
            <div class="card-subtitle">판매자: <%= item.user&.email %></div>
            <p class="card-text"><%= item.description.truncate(15) %></p>
            <p class="text-muted"><%= number_with_delimiter item.price %>원</p>
            <%= link_to "자세히 보기", item_path(item), class: "btn btn-primary btn-sm" %>

          </div>
          <div class="card-footer">
            <% if item.user == current_user %>
              <%= link_to "수정", edit_item_path(item), class: "btn btn-secondary btn-sm"%>
              <%= link_to "삭제", item, method: :delete, data: {confirm: "정말로 삭제하시겠습니까?"}, class: "btn btn-danger btn-sm" %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%= paginate @items  %>
</div>

app/views/items/new.html.erb
<%= render "form" %>

app/views/items/show.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-md-4">
      <%= image_tag @item.image.url, class: "img-thumbnail img-fluid" %>
    </div>
    <div class="col-md-8">
      <h4><%= @item.title %></h4>
      <p><%= number_with_delimiter @item.price %>원</p>
      <%= link_to current_user&.has_item?(@item) ? "찜취소하기" : "찜하기", toggle_item_path(@item), class: "btn btn-primary" %>
      <%= link_to "장바구니 담기", add_item_path(@item), class: "btn btn-secondary" %>
      <!-- edit액션 대신 add 또는 orders 컨트롤러의 액션 등을 사용할 수 있으나 itesms#edit 액션을 사용할 일이 없으므로 대신 사add -->
    </div>
  </div>
  <div class="row mt-3">
    <div class="col-12">
      <%= simple_format @item.description %>
    </div>
  </div>
  <% if current_user %>
  <%= render "comments/form", comment: Comment.new, item: @item, user: current_user %>
  <% end %>
  <hr>

  <%= render 'comments/comments', comments: @item.comments.order(created_at: :desc) %>
  <hr>
  <%= link_to "뒤로가기", items_path %>
</div>

app/views/line_items/destroy.js.erb
alert("삭제되었습니다.");
$(".card[data-id='<%= @line_item.id %>']").remove();
$(".amount-total").html("<%= j(render 'orders/total_amount', order: @line_item.order) %>");

<% if @line_item.order.total == 0 %>
  $(".cart").html('<div class="card p-3 text-center">장바구니가 비어있습니다.</div>');
<% end %>

app/views/orders/_total_amount.html.erb
<% order ||= nil %>
<% if order %>
  <p>
    총 금액: <%= number_with_delimiter order.total %>원
  </p>
<% end %>

app/views/orders/edit.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col">
      <div class="card p-5">
        <h2>주문 정보 입력</h2>
        <hr>
        <%= form_for @order do |f| %>
          <div class="form-group">
            <%= f.label :zipcode %>
            <%= f.text_field :zipcode, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :address1 %>
            <%= f.text_field :address1, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :address2 %>
            <%= f.text_field :address2, class: "form-control" %>
          </div>
          <%= f.submit "결제하기", class: "btn btn-primary"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/orders/index.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col">
      <% @orders.each do |order| %>
        <div class="card p-3 mb-3">
          <% order.line_items.each do |line_item| %>
            <% if item = line_item.item %>
              <%= line_item.item.title %> (<%= number_with_delimiter(line_item.price) %>원 * <%= line_item.amount %>개)
            <% else %>
              삭제된 상품입니다.
            <% end %>
          <% end %>
            <hr>
          <%= number_with_delimiter order.total %>원
        </div>
      <% end %>
      <%= paginate @orders %>
    </div>
  </div>
</div>

app/views/orders/new.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-12 cart">
      <% if @order.line_items.blank? %>
        <div class="card p-3 text-center">
          장바구니가 비어있습니다.
        </div>
      <% else %>
        <% @order.line_items.each do |line_item| %>
        <!-- $(".card[data-id='']") -->
          <div class="card mb-3" data-id="<%= line_item.id %>">
            <div class="card-body">
              <div class="row">
                <div class="col-6 align-self-center">
                  <%= line_item.item.title %>
                </div>
                <div class="col-2 align-self-center"><%= line_item.amount %></div>
                <div class="col-3 text-right align-self-center"><%= number_with_delimiter line_item.amount * line_item.price %>원</div>
                <div class="col-1 text-right align-self-center">
                  <%= link_to line_item, method: :delete, data: {confirm: "정말로 삭제하시겠습니까?"}, class: "btn btn-secondary btn-xs", remote: true do %>
                    <span class="span">X</span>
                  <% end %>
                </div>
              </div>
              <%# hidden_field_tag :item_id, line_item.id %>
            </div>
          </div>
        <% end %>
        <div class="amount-total">
          <%= render 'total_amount', order: @order %>
        </div>
        <%= link_to "주문하기", edit_order_path(@order), class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>


<script>
  // setTimeout(function(){
  //   $.ajax({
  //     url: "<%= root_path %>",
  //     method: "GET",
  //     data:{
  //       line_item_id: "<%= 123123 %>"
  //     },
  //     content: "javascript/application"
  //   }).done(function(){
  //     alert("ajax completed")
  //   })
  // },3000)

</script>

app/views/orders/show.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col">
      <div class="card p-5">
        <%= number_with_delimiter @order.total %>원
      </div>
    </div>
  </div>
</div>

app/views/user_items/index.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-12 mb-2">
      <h2>찜한 상품</h2>
      <hr>
    </div>
    <% @user_items.each do |user_item| %>
      <% if item = user_item.item %>
        <div class="col-md-3 mb-4">
          <div class="card">
            <img class="card-img-top" src="<%= item.image.url(:thumb) if item.image? %>"  alt="Card image cap">
            <div class="card-body">
              <h5 class="card-title"><%= item.title %></h5>
              <div class="card-subtitle">판매자: <%= item.user&.email %></div>
              <p class="card-text"><%= item.description %></p>
              <%= link_to "자세히 보기", item, class: "btn btn-primary btn-sm" %>
              <% if item.user == current_user %>
                <%= link_to "수정", edit_item_path(item), class: "btn btn-secondary btn-sm"%>
                <%= link_to "삭제", item, method: :delete, data: {confirm: "정말로 삭제하시겠습니까?"}, class: "btn btn-danger btn-sm" %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= paginate @user_items  %>
</div>