config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  resources :items do
    member do
      get :toggle # 찜하기
      get :add # 장바구니 추가
    end
  end

  resources :orders
  resources :line_items
  resources :user_items
  resources :comments
  root "items#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  def self.generate_categories
    %w(식품/생활
    패션/뷰티
    가전/디지털
    여행/레저).each_with_index do |category_title, index|
      Category.create(title: category_title, position: index)
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :item, optional: true
end

app/models/item.rb
class Item < ApplicationRecord
  mount_uploader :image, ImageUploader

  belongs_to :user, optional: true
  belongs_to :category, optional: true

  has_many :line_items, dependent: :nullify
  # 상품이 삭제되도 주문 항목은 삭제되면 안 됨
  has_many :user_items, dependent: :destroy
  # 찜하기는 상품이 삭제되면 삭제되어도 됨(어차피 삭제된 상품 확인할 수 없음)

  has_many :comments, dependent: :destroy

  def self.generate_items
    %w(아이폰 안드로이드 아이패드 맥북 시계 애플워치 갤럭시기어).each do |title|
      category = Category.first
      Item.create(title: title, price: 2000000, category: category, image: Item.first.image, user: User.first)
    end
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :item, optional: true

  # 상품이 삭제되어도 기존에 주문한 주문 항목은 남아있어야 해서 optional로 정의하고
  # item 쪽에 has_many 할 떄는 destroy 대신 nullify

  # line_item이 변경될 떄마다 주문의 총 가격 변경하기
  # line_item 본인을 변경할 때는 after_save 후 update 하지 말고(재귀함수처럼 계속)
  # before_save 하고 update 대 = 로 할당만 해서 save할 때 한 번에 저장되도록 처리하는 것이 좋음

  # line_item 본인이 아니라 order를 수정하는 것이므로  after_save 후 order.update를 해도 될듯

  # after_save :set_order_total
  after_destroy :set_order_total

  def set_order_total
    puts "set_order_total"
    order.update(total: order.line_items.sum("amount * price"))
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, optional: true
  enum status: [:cart, :paid, :canceled]

  has_many :line_items, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_items, dependent: :destroy # 찜하기는 회원이 삭제되거나 탈퇴하면 지워져도 됨
  has_many :items, dependent: :nullify # 등록된 상품은 등록한 회원이 삭제되더라도
  # 주문이나 리뷰 등 다른 데이터와 많이 엮여 있어서 삭제하지 않고 foreign_key만 null로 갱신

  has_many :comments, dependent: :nullify

  has_many :orders
  def has_item? item
    user_items.where(item: item).present?
  end
end

app/models/user_item.rb
class UserItem < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create comment_params
    # redirect_to item_path(comment.item)
  end

  def update
    comment = Comment.find_by(id: params[:id])
    comment.update(commnet_params) if comment
    redirect_to item_path(comment.item)
  end

  def destroy
    @comment = Comment.find_by(id: params[:id])
    # byebug
    @comment.destroy if @comment
    # redirect_to item_path(comment.item)
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :user_id, :item_id)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show] # 찜하기 로그인 해야 사용 가능
  before_action :load_object, only: [:show, :toggle, :edit, :update, :destroy, :add] # 상품 상세와 찜하기는 @item을 먼저 불러옴
  before_action :check_owner, only: [:edit, :update, :destroy] # 수정/삭제는 상품 소유자만 할 수 있도록

  def index
    # 내가 판매하는 상품
    if params[:type] == "selling"
      redirect_to root_path, notice: "로그인을 해야 합니다" unless current_user
      @items = current_user.items
    else
      @items = Item.all
      # 카테고리별 페이지
      if params[:category_id].present?
        @category = Category.find(params[:category_id])
        @items = @items.where(category_id: params[:category_id])
      end
    end
    # byebug
    @items = @items.ransack(title_or_description_cont: params[:q]).result(distinct: true) if params[:q].present?
    @items = params[:order].blank? ? @items.order(created_at: :desc) : @items.order(params[:order])
    @items = @items.page(params[:page]).per(20)
  end

  def toggle
    if user_item = current_user.user_items.where(item: @item).first
      # 이미 찜한 상태라면 해제
      user_item.destroy
      flash[:notice] = "찜을 제거하였습니다."
    else
      # 찜한 상태가 아니면 찜하기
      current_user.user_items.where(item: @item).create
      flash[:notice] = "찜하였습니다."
    end
    redirect_to @item
  end

  def add
    # edit은 판매자가 상품 편집을 하는데 사용
    @order = get_cart
    # orders_controller.rb
      # def get_cart
      #   # 현재 로그인한 유저가 가진 주문 중 cart 상태의 주문을 하나 찾아서 가져오거나
      #   # 없으면 하나 새로 생성함
      #   current_user.orders.cart.first_or_create
      # end
      # byebug
    line_item = @order.line_items.where(item: @item).first_or_create(price: @item.price)
    line_item.increment!(:amount)
    line_item.set_order_total
    # line_item.rb
      # def set_order_total
      #   order.update(total: order.line_items.sum("amount * price"))
      # end
    redirect_to new_order_path, notice: "장바구니에 상품을 담았습니다."
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.create(item_params)
    # @item.update(user: current_user)
    redirect_to items_path(type: :selling), notice: "상품을 등록했습니다."
  end

  def edit
  end

  def update
    @item.update(item_params)
    redirect_to items_path(type: :selling), notice: "상품을 수정했습니다."
  end

  def destroy
    @item.destroy
    redirect_back fallback_location: root_path
  end

  def show
  end

  private

    def load_object
      @item = Item.find params[:id]
    end

    def item_params
      params.require(:item).permit(:title, :price, :description, :image, :category_id, :user_id)
    end

    def check_owner
      redirect_to root_path, notice: "권한이 없습니다." unless @item.user == current_user
    end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  def destroy
    @line_item = LineItem.find(params[:id])
    @line_item.destroy
    

    # @order = Order.find(params[:id])
    # redirect_back fallback_location: root_path
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  # 다른 사람도 주문 아이디만 알면 접근이 간으한 상태이므로 내 주문은 나만 볼수 있도 권한 체크
  before_action :load_object, :check_owner, only: [:edit, :show, :update]


  def new
    @order = get_cart
    
  end

  def edit

  end

  def update
    @order.paid!
    @order.update(paid_at: Time.now)
    redirect_to @order
  end

  def index
    @orders = current_user.orders.order(:paid_at).page(params[:page]).per(10)
  end

  private

  def load_object
    @order = Order.find(params[:id])
  end

  def check_owner
    redirect_to(root_path, notice: "권한이 없습니다") unless (@order.user == current_user)
  end
end

app/controllers/user_items_controller.rb
class UserItemsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user_items = current_user.user_items.page(params[:page]).per(10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/user_items_helper.rb
module UserItemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Market</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application'%>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if notice %>
      <div class="alert alert-success">
        <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-danger">
        <%= alert %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <%= render "shared/header" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container">
    <a class="navbar-brand" href="/">MARKET</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-between" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <% Category.order(:position).each do |category| %>
          <li class="nav-item">
            <a class="nav-link <%= params[:category_id].to_i == category.id ? "active" : "" %>" href="<%= items_path(category_id: category.id) %>"><%= category.title %></a>
          </li>
        <% end %>
      </ul>
      <ul class="navbar-nav">
        <% if current_user %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              마이페이지
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="<%= new_order_path %>">장바구니</a>
              <a class="dropdown-item" href="<%= user_items_path %>">찜한 상품</a>
              <a class="dropdown-item" href="<%= orders_path %>">내 주문</a>
              <a class="dropdown-item" href="<%= items_path(type: :selling) %>">내 상품</a>
              <a class="dropdown-item" href="<%= edit_user_registration_path %>">회원정보수정</a>
            </div>
          </li>
          <li class="nav-item">
            <%= link_to "로그아웃", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <a class="nav-link active" href="<%= new_user_session_path %>">로그인</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="<%= new_user_registration_path %>">회원가입</a>
          </li>
        <% end %>




      </ul>
    </div>
  </div>
</nav>